[env:waveshare_s3_lcd_21]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
upload_speed = 115200

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_USE_LOG=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM

lib_deps =
    lvgl/lvgl@8.4.0
    bblanchon/ArduinoJson@^7.0.4

board_build.filesystem = littlefs