#pragma once

#define PROJECT_NAME "DRILLVISION"
#define PROJECT_VERSION "V5.00"

#define HARDWARE_WAVESHARE_S3 1
#define ACTIVE_HARDWARE HARDWARE_WAVESHARE_S3

#define SENSOR_MODE_SIMULATION 0
#define SENSOR_MODE_QMI8658 1

#define ACTIVE_SENSOR_MODE SENSOR_MODE_SIMULATION

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 480

#define DISPLAY_CENTER_X 240
#define DISPLAY_CENTER_Y 240